version: "3"
services:
  moqui-app:
    image: moqui
    container_name: moqui-app
    command: conf=conf/MoquiProductionConf.xml
    restart: unless-stopped
    links:
     - moqui-database
    ports:
     - 8080:8080
    volumes:
     - /fileRepo:/fileRepo
     - ./runtime:/opt/moqui/runtime
     - /etc/localtime:/etc/localtime
    environment:
     - instance_purpose=production
     - entity_ds_db_conf=mysql
     - entity_ds_host=moqui-database
     - entity_ds_port=3306
     - entity_ds_database=mci
     - entity_ds_user=sajaya  
     - entity_ds_password=Sima@110
     - entity_ds_crypt_pass='MoquiDefaultPassword:CHANGEME'
     # moqui will accept traffic from other hosts but these are the values used for URL writing when specified:
     - webapp_http_host=192.168.75.22
     - webapp_http_port=8080
     #- webapp_https_port=443
     #- webapp_https_enabled=true
     - default_locale=en_US
     - default_time_zone=Asia/Tehran
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "4"

  moqui-database:
    image: mysql:8.0
    container_name: moqui-database
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=1 --sql_mode="" --innodb-buffer-pool-size=20G
    #ports:
     # change this as needed to bind to any address or even comment to not expose port outside containers
    # - 3306:3306
    expose:
     - 3306
    volumes:
     # edit these as needed to map configuration and data storage
     - /opt/database/mysql/:/var/lib/mysql
     # - /my/mysql/conf.d:/etc/mysql/conf.d
    environment:
     - MYSQL_ROOT_PASSWORD=mciDBpass@110
     - MYSQL_DATABASE=mci
     - MYSQL_USER=sajaya
     - MYSQL_PASSWORD=Sima@110
  
  nginx-proxy:
    # For documentation on SSL and other settings see:
    # https://github.com/jwilder/nginx-proxy
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 9090:9090
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # note: .crt, .key, and .dhparam.pem files start with the domain name in VIRTUAL_HOST (ie 'moqui.local.*') or use CERT_NAME env var
      - ./certs:/etc/nginx/certs
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /opt/ui/build:/opt/ui:ro
      - /opt/vitrin/build:/opt/vitrin:ro
